import type { Metadata } from "next";
import { Baskervville } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar";

const baskervville = Baskervville({
  subsets: ["latin"],
  variable: "--font-baskervville",
  display: "auto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${baskervville.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
